### ISSUE TITLE
[Bug]: RAY error

### ISSUE THREAD

**Issue by simplew2011** [alibaba/data-juicer#129]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubuntu

### Installation Method 安装方式

 from source

### Data-Juicer Version Data-Juicer版本

v0.1.2

### Python Version Python版本

3.8

### Describe the bug 描述这个bug

language_id_score_filter算子
-   --executor_type ray，报错
-   --executor_type default，正常

### To Reproduce 如何复现

python tools/process_data.py --config configs/demo/process.yaml  --executor_type ray

### Configs 配置信息

```
project_name: 'demo-process'
dataset_path: 'demos/process_on_ray/data/demo-dataset.json'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

export_path: './outputs/demo-process/demo-processed.jsonl'

use_cache: false
save_stats_in_one_file: true

# process schedule
# a list of several process operators with their arguments
process:
  - language_id_score_filter:
      lang: 'zh'
```

### Logs 报错日志

[outputs.zip](https://github.com/alibaba/data-juicer/files/13643288/outputs.zip)

### Screenshots 截图

![image](https://github.com/alibaba/data-juicer/assets/66729924/fd10f9d8-0e4e-469c-a496-68656ee85baa)

**Comment by simplew2011** [comment]
#107

**Comment by zhijianma** [comment]
`export_path ` 请先使用绝对路径。 ray 在保存时，暂时无法写入相对路径。
后边我们也会增强一下。

**Comment by simplew2011** [comment]
- export_path 设置为绝对路径，上面正常了；
- 但使用另一个算子，ray模式又报错了，default模式正常
- python tools/process_data.py --config configs/demo/process.yaml  --executor_type ray

```yaml
# Process config example for dataset

# global parameters
project_name: 'demo-process'
dataset_path: '/home/wzp/code/LLMData/open_source/data-juicer/demos/process_on_ray/data/demo-dataset.json'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

export_path: '/home/wzp/code/LLMData/open_source/data-juicer/outputs/demo-process/demo-processed.jsonl'

# use_cache: false
# save_stats_in_one_file: true

# process schedule
# a list of several process operators with their arguments
process:
  # - language_id_score_filter:
  #     lang: 'zh'
  # - alphanumeric_filter:
  - chinese_convert_mapper:
      mode: 's2t'
```

```
NameError: name 'OPENCC_CONVERTER' is not defined

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/loguru/_handler.py", line 204, in emit
    self._queue.put(str_record)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/multiprocessing/queues.py", line 362, in put
    obj = _ForkingPickler.dumps(obj)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'ray.exceptions.RayTaskError(NameError)'>: attribute lookup RayTaskError(NameError) on ray.exceptions failed
--- End of logging error ---
```
[outputs2.zip](https://github.com/alibaba/data-juicer/files/13646364/outputs2.zip)
