### ISSUE TITLE
如何修改data-juicer的数据处理字段由“text”变为其他？

### ISSUE THREAD

**Issue by newlinfeng-coder** [alibaba/data-juicer#158]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

如题，处理字段参数text可以修改吗？

**Comment by HYLcool** [comment]
你好，感谢你的关注与使用~

你可以通过修改配置文件中的text_keys全局参数来指定整个处理流程的处理字段，如：
https://github.com/alibaba/data-juicer/blob/7a0e23336f25926a568362d60a18544bbc8496c7/configs/config_all.yaml#L13

此外，你也可以单独为某个OP设置text_key参数特别指定这个OP要处理的字段，如：
```yaml
process:
- language_id_score_filter:
      lang: en
      min_score: 0.8
      text_key: 'input'  # 这个算子只对input字段进行处理，其他未设置的算子对全局参数text_keys指定的字段进行处理
```

你可以尝试一下，有其他进一步的问题可随时讨论~
