### ISSUE TITLE
[Bug]:  ChineseWebText dataset process error

### ISSUE THREAD

**Issue by simplew2011** [alibaba/data-juicer#161]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubuntu

### Installation Method 安装方式

 from source

### Data-Juicer Version Data-Juicer版本

v0.1.2

### Python Version Python版本

3.8

### Describe the bug 描述这个bug

数据集：https://hf-mirror.com/datasets/CASIA-LM/ChineseWebText/tree/main/ChineseWebText/2021-43

'text'字段数据格式是一个字符串列表，形如：[['字符串1'， '字符串2']]，在下行会报错：https://github.com/alibaba/data-juicer/blob/main/data_juicer/ops/mapper/nlpcda_zh_mapper.py#L149

```
  File "/home/vastai/simplew/data-juicer/data_juicer/ops/mapper/nlpcda_zh_mapper.py", line 149, in process
    aug_texts += aug_method.replace(texts_to_aug[0])[1:]
  File "/home/vastai/anaconda3/envs/3.8/lib/python3.8/site-packages/nlpcda/tools/Similar_word.py", line 34, in replace
    replace_str = replace_str.replace('\n', '').strip()
AttributeError: 'list' object has no attribute 'replace'
```

当前应该只支持['字符串1']格式，可以完善下，支持二级列表

### To Reproduce 如何复现

dj-process --config configs/demo/process.yaml

### Configs 配置信息

```
# Process config example for dataset

# global parameters
project_name: 'demo-process'
dataset_path: 'ChineseWebText/2021-43'  # path to your dataset directory or file
np: 48  # number of subprocess to process your dataset

export_path: './outputs/demo-process/demo-processed.jsonl'

# process schedule
# a list of several process operators with their arguments
process:

  - nlpcda_zh_mapper:                                       # simply augment texts in Chinese based on the nlpaug library
      sequential: false                                       # whether combine all augmentation methods to a sequence. If it's True, a sample will be augmented by all opened augmentation methods sequentially. If it's False, each opened augmentation method would generate its augmented samples independently.
      aug_num: 1                                              # number of augmented samples to be generated. If `sequential` is True, there will be total aug_num augmented samples generated. If it's False, there will be (aug_num * #opened_aug_method) augmented samples generated.
      replace_similar_word: true 
```
