### ISSUE TITLE
去重50G左右中文语料卡死

### ISSUE THREAD

**Issue by YaboSun** [alibaba/data-juicer#30]
使用项目进行中文语料去重(minhash)等算子操作，在去重阶段卡死，约4000w条数据
详细配置如下：
```
project_name: 'CC100-zh'
dataset_path: xxx.jsonl
export_path: xxx-processed.jsonl

np: 50
open_tracer: true
text_keys: 'text'
process:
  - perplexity_filter:
      lang: zh
      max_ppl: 2500
  - document_minhash_deduplicator:                          
      tokenization: character                                    
      window_size: 5                                        
      num_permutations: 256                                   
      jaccard_threshold: 0.7                                 
      num_bands: null                                        
      num_rows_per_band: null                                 
      lowercase: true                                         
      ignore_pattern: null                                    
  - text_length_filter:
      min_len: 200
      max_len: 65589
  - character_repetition_filter:
      rep_len: 10
      max_ratio: 0.3
  - word_repetition_filter:
      lang: zh
      tokenization: true
      rep_len: 10
      max_ratio: 0.279
```

另外想问一下是否有处理类似规模语料详细的耗时统计？
