### ISSUE TITLE
[Bug]: NameError: name 'fingerprint_warnings' is not defined  TypeError: cannot pickle 'OpenCC' object

### ISSUE THREAD

**Issue by simplew2011** [alibaba/data-juicer#81]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubuntu

### Installation Method 安装方式

pip

### Data-Juicer Version Data-Juicer版本

v0.1.2

### Python Version Python版本

3.8

### Describe the bug 描述这个bug

![image](https://github.com/alibaba/data-juicer/assets/66729924/2f12490e-efe4-462f-aed1-390a44ac7275)

### To Reproduce 如何复现

```
# configs/demo/process.yaml

# global parameters
project_name: 'demo-process'
dataset_path: './demos/data/demo-dataset.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

export_path: './outputs/demo-process/demo-processed.jsonl'

# process schedule
# a list of several process operators with their arguments
process:
  # - language_id_score_filter:
  #     lang: 'zh'
  - chinese_convert_mapper:
        mode: 's2t'
```

```
python tools/process_data.py --config configs/demo/process.yaml
```
报错如上面截图

使用以下单独脚本测试是正常的：
```
from data_juicer.ops.mapper.chinese_convert_mapper import ChineseConvertMapper

text = {"text": "我在馬路邊嫲緑變"}

op = ChineseConvertMapper(mode = 't2s')

aa = op.process(text)
print(aa)
```
